print("Welcome to Python-Shopping-Assistant, What is your name?")
nickname = input("Enter your nickname: ")
if len(nickname) > 12:
    print("Your nickname must be 12 characters.")
elif not nickname.replace(" ", "").isalpha():
    print("Your nickname must only contain letters.")
elif " " in nickname:
    print("Your nickname must not contain spaces.")
    nickname = nickname.replace(" ", "")
    print(f"Welcome {nickname.capitalize()} to Python!")
else:
    print(f"Welcome {nickname.capitalize()}!")

buy = input(f"What are you buying {nickname.capitalize()}?: ")

print(f"Alright, you are going to get {buy}.")
print("I will help you with that.")

item1 = input("What is item 1?: ")
price1 = float(input(f"What is the price of {item1}?: "))
answer= input("Is that all?(Y/N): ")
if answer.upper() == "Y":
    print(f"Your total is {price1}, here is what you bought: {item1}.")
    print(f"Thank you for shopping with us {nickname}! See you again next time.")
else:
    item2 = input("What is item 2?: ")
    price2 = float(input(f"What is the price of {item2}?: "))
    answer = input("Is that all?(Y/N): ")
    if answer.upper() == "Y":
        print(f"Your total is {price1+price2:,.2f}php Here is the list of what you bought: ")
        print(item1)
        print(item2)
        print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
    else:
        item3 = input("What is item 3?: ")
        price3 = float(input(f"What is the price of {item3}?: "))
        answer = input("Is that all?(Y/N): ")
        if answer.upper() == "Y":
            print(f"Your total is {price1+price2+price3:,.2f}, here is a list of what you bought: ")
            print(item1)
            print(item2)
            print(item3)
            print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
        else:
            item4 = input("What is item 4?: ")
            price4 = float(input(f"What is the price of {item4}?: "))
            answer = input("Is that all?(Y/N): ")
            if answer.upper() == "Y":
                print(f"Your total is {price1 + price2+ price3 + price4:,.2f}, here is a list of what you bought: ")
                print(item1)
                print(item2)
                print(item3)
                print(item4)
                print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
            else:
                item5 = input("What is item 5?: ")
                price5 = float(input(f"What is the price of {item5}?: "))
                answer = input("Is that all?(Y/N): ")
                if answer.upper() == "Y":
                    print(f"Your total is {price1 + price2 + price3 + price4+price5:,.2f}, here is a list of what you bought: ")
                    print(item1)
                    print(item2)
                    print(item3)
                    print(item4)
                    print(item5)
                    print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
                else:
                    item6 = input("What is item 6?: ")
                    price6 = float(input(f"What is the price of {item6}?: "))
                    answer = input("Is that all?(Y/N): ")
                    if answer.upper() == "Y":
                        print(f"Your total is {price1 + price2 + price3 + price4 + price5 + price6:,.2f}, here is a list of what you bought: ")
                        print(item1)
                        print(item2)
                        print(item3)
                        print(item4)
                        print(item5)
                        print(item6)
                        print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
                    else:
                        item7 = input("What is item 7?: ")
                        price7 = float(input(f"What is the price of {item7}?: "))
                        answer = input("Is that all?(Y/N): ")
                        if answer.upper() == "Y":
                            print(f"Your total is {price1 + price2 + price3 + price4 + price5 + price6 + price7:,.2f}, here is a list of what you bought: ")
                            print(item1)
                            print(item2)
                            print(item3)
                            print(item4)
                            print(item5)
                            print(item6)
                            print(item7)
                            print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
                        else:
                            item8 = input("What is item 8?: ")
                            price8 = float(input(f"What is the price of {item8}?: "))
                            answer = input("Is that all?(Y/N): ")
                            if answer.upper() == "Y":
                                print(f"Your total is {price1 + price2 + price3 + price4 + price5 + price6 + price7 + price8:,.2f}, here is a list of what you bought: ")
                                print(item1)
                                print(item2)
                                print(item3)
                                print(item4)
                                print(item5)
                                print(item6)
                                print(item7)
                                print(item8)
                                print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
                            else:
                                item9 = input("What is item 9?: ")
                                price9 = float(input(f"What is the price of {item9}?: "))
                                answer = input("Is that all?(Y/N): ")
                                if answer.upper() == "Y":
                                    print(f"Your total is {price1 + price2 + price3 + price4 + price5 + price6 + price7 + price8 + price9:,.2f}, here is a list of what you bought: ")
                                    print(item1)
                                    print(item2)
                                    print(item3)
                                    print(item4)
                                    print(item5)
                                    print(item6)
                                    print(item7)
                                    print(item8)
                                    print(item9)
                                    print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")
                                else:
                                    item10 = input("What is item 10?: ")
                                    price10 = float(input(f"What is the price of {item10}?: "))
                                    print("Items are maximized. Calculating.")
                                    print(f"Your total is {price1 + price2 + price3 + price4 + price5 + price6 + price7 + price8 + price9 + price10:,.2f}, here is a list of what you bought: ")
                                    print(item1)
                                    print(item2)
                                    print(item3)
                                    print(item4)
                                    print(item5)
                                    print(item6)
                                    print(item7)
                                    print(item8)
                                    print(item9)
                                    print(item10)
                                    print(f"Thank you for shopping with us {nickname.capitalize()}! See you again next time.")